### PR TITLE
fix: consistent variadic argument support in all loggers

### LINKED ISSUE #16: log stack trace if input is Error?
currently logging an Error with the debug doesn't log the stack trace while console does.
Should we support this?

### LINKED ISSUE #21: logging should pretty print objects
`console.log(obj1 [, obj2, ..., objN])`

console.log outputs a hson representation of each object passed to it.

```
console.log('resolver got request: ', request)
aioLogger.debug('resolver got request: ', request)
```

```
// console.log output:
2020-03-10T23:00:56.312Z       stdout: resolver got request:  { org: 'asdsomeorg@AdobeOrg',
  path: '/',
  clientId: 'aio-app-myapple',
  tenant: '3124',
  imsProfile: ...
  ...
}
// aioLogger.debug output:
2020-03-10T23:00:56.313Z       stdout: 2020-03-10T23:00:56.312Z @adobe/aio-app-myapps/resolver:debug resolver got request:
```

### PR DESCRIPTION
**Pull request by shazron**
Closes #21 - however since it is using util.inspect, there is [no indenting of json objects](https://github.com/nodejs/node/issues/14638)
Closes #16 

## How Has This Been Tested?

npm test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by MichaelGoberling — APPROVED** [review]
LGTM! 

(Also TIL I am a mountain climber ⛰️ )

**Comment by shazron** [comment]
> LGTM!
d'oh! it was a nice exercise, but I just realized I was just re-implementing node:util.format 😱  Reworking this PR

**Comment by shazron** [comment]
Fixed 😅 (build failures because of eslint-plugin-import 2.27.0, which is pending a patch)

**Review by moritzraho — APPROVED** [review]
Lgtm! (and learn about`util.format` myself 🙂 )

**Pull request merged**
